### ISSUE TITLE
Errors when using dictionnary to specify alternate commands 

### ISSUE THREAD

**Issue by gitUser000** [epsy/clize#101]
Hi,

Thanks for this project....

I am reading examples from documentation and get problem/error trying to use  dictionnary as alternate commands list.

Following is the code (mainly copied from documentation) and the errors i get.

What i am doing wrong ? 

```python 

from clize import ArgumentError, Parameter, run

VERSION = "0.2"

#------------------------------------------------------------------------------
def echo(*text:Parameter.REQUIRED,
            prefix:'p'='', suffix:'s'='', reverse:'r'=False, repeat:'n'=1):
    """Echoes text back

    :param text: The text to echo back
    :param reverse: Reverse text before processing
    :param repeat: Amount of times to repeat text
    :param prefix: Prepend this to each line in word
    :param suffix: Append this to each line in word
    """
    text = ' '.join(text)

    if 'spam' in text:
        raise ArgumentError("I don't want any spam!")

    if reverse:
        text = text[::-1]

    text = text * repeat

    if prefix or suffix:
        return '\n'.join(prefix + line + suffix for line in text.split('\n'))

    return text

#------------------------------------------------------------------------------
def version():
    """Show the version"""
    return (f"version={VERSION}")

#------------------------------------------------------------------------------
def build_date(*,show_time=False):
    """Show the build date for this version"""
    print("Build date: 17 August 1979", end='')
    if show_time:
        print(" afternoon, about tea time")
    print()


#------------------------------------------------------------------------------
if __name__ == '__main__':
    # next is OK
    # run(echo, alt=[version, build_date])
    # this not working 
    run(echo,  alt= 
        {   "totally_not_the_version": version,
            "birth": build_date
        })
```

Tested with python 3.6.9 and 3.9.0

```bash
cd /home/user/MyPyProjs/Py390/CliTests
venv_activate
(venv) > python clize_t01.py

Traceback (most recent call last):
  File "/home/user/MyPyProjs/Py390/CliTests/clize_t01.py", line 51, in <module>
    run(echo, alt={
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/sigtools/modifiers.py", line 161, in __call__
    return self.func(*args, **kwargs)
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/runner.py", line 395, in run
    ret = cli(*args)
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/runner.py", line 261, in __call__
    func, name, posargs, kwargs = self.read_commandline(args)
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/runner.py", line 271, in read_commandline
    ba = self.signature.read_arguments(args[1:], args[0])
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/util.py", line 121, in __get__
    ret = obj.__dict__[self.key] = self.func(obj)
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/runner.py", line 220, in signature
    return parser.CliSignature.from_signature(
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/parser.py", line 1143, in from_signature
    return cls(
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/parser.py", line 1107, in __init__
    for param in _develop_extras(parameters):
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/parser.py", line 1052, in _develop_extras
    for param in params:
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/runner.py", line 252, in _process_alt
    for name, func in util.dict_from_names(alt).items():
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/util.py", line 104, in dict_from_names
    receiver.update((x.__name__, x) for x in maybe_iter(obj))
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/util.py", line 104, in <genexpr>
    receiver.update((x.__name__, x) for x in maybe_iter(obj))
AttributeError: 'str' object has no attribute '__name__'
```

**Comment by gitUser000** [comment]
Hi, thanks for update.

I dont know if it is related (and maybe it is 'normal') but i also found this "problem" : 

Using description WITH alternate command list won't works 

Using previously typed code  : 

```python
    # CASE A -> OK
    run(echo, version, build_date, description="""
        test description
        """)

    # CASE B -> Not OK
    run(echo, alt=[version, build_date], description="""
        test description
        """)
```

Case B provide error : 


```bash
Traceback (most recent call last):
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/runner.py", line 172, in get_cli
    cli = obj.cli
AttributeError: 'function' object has no attribute 'cli'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/MyPyProjs/Py390/CliTests/./clize_t01.py", line 53, in <module>
    run(echo, description="""
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/sigtools/modifiers.py", line 161, in __call__
    return self.func(*args, **kwargs)
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/runner.py", line 381, in run
    cli = Clize.get_cli(fn, **kwargs)
  File "/home/user/MyPyProjs/Py390/CliTests/venv/lib/python3.9/site-packages/clize/runner.py", line 175, in get_cli
    cli = cls(obj, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'description'
```

**Comment by gitUser000** [comment]
When you put it like that, the difference between A and B makes a lot of sense... 
Thank you for your responsiveness and the new release.
👍
