### ISSUE TITLE
What is going wrong here?

### ISSUE THREAD

**Issue by ericchansen** [epsy/clize#79]
I'm having a hard time interpreting what's wrong based on the error message. Can anyone throw me a bone? Or maybe it's a bug?

Here's all the code you need.

```
from pathlib import Path
from typing import List, Optional, Union

from clize import run


def clize_demo(
    one_path_or_many_paths: Union[Path, List[Path]],
    optional_path: Optional[Path] = None,
    optional_int: Optional[int] = None,
    bool_with_default: bool = False,
):
    pass


if __name__ == "__main__":
    run(clize_demo)
```

Here's what you get when you try it out.

```
(venv-clize) me@neato:~/repos/clive-demo$ python wow.py
Traceback (most recent call last):
  File "wow.py", line 17, in <module>
    run(clize_demo)
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/sigtools/modifiers.py", line 158, in __call__
    return self.func(*args, **kwargs)
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/runner.py", line 363, in run
    ret = cli(*args)
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/runner.py", line 219, in __call__
    func, name, posargs, kwargs = self.read_commandline(args)
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/runner.py", line 229, in read_commandline
    ba = self.signature.read_arguments(args[1:], args[0])
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/util.py", line 128, in __get__
    ret = obj.__dict__[self.key] = self.func(obj)
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/runner.py", line 195, in signature
    return parser.CliSignature.from_signature(
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/parser.py", line 998, in from_signature
    return cls(
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/parser.py", line 962, in __init__
    for param in _develop_extras(parameters):
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/parser.py", line 907, in _develop_extras
    for param in params:
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/parser.py", line 1001, in <genexpr>
    (cls.convert_parameter(param)
  File "/home/me/virtualenvs/venv-clize/lib/python3.8/site-packages/clize/parser.py", line 1013, in convert_parameter
    if Parameter.IGNORE in annotations:
  File "/usr/lib/python3.8/typing.py", line 261, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.8/typing.py", line 685, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.8/typing.py", line 685, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "/usr/lib/python3.8/typing.py", line 149, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got 0.
```

**Comment by epsy** [comment]
Sorry, `typings` annotations are not supported yet (and you're right, clize isn't giving you a very good error message for it.)

Here's a version of your code that runs successfully, though because the annotations don't match what `typings` expects, you'll have to use its `no_type_check` decorator.

```python
from pathlib import Path
from typing import no_type_check

from clize import run

@no_type_check
def clize_demo(
    *one_path_or_many_paths: Path,
    optional_path: Path = None,
    optional_int: int = None,
    bool_with_default: bool = False,
):
    pass


if __name__ == "__main__":
    run(clize_demo)
```

```
$ python3.9 clizetest.py --help
Usage: clizetest.py [OPTIONS] [one-path-or-many-paths...]

Arguments:
  one-path-or-many-paths...    (type: PATH)

Options:
  --bool-with-default
  --optional-int=INT
  --optional-path=PATH

Other actions:
  -h, --help                  Show the help
```

**Comment by ericchansen** [comment]
Thanks @epsy. Your minimal example works. We're going to have to pass on using clize as long as it doesn't support modern typing.
